services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    pull_policy: always
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: []
    command: ["ollama", "serve"]

  ollama-cpu:
    image: ollama/ollama:latest
    container_name: ollama-cpu
    ports:
      - "127.0.0.1:11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    pull_policy: always
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_USE_CPU=true  # or whatever flag disables GPU usage
    entrypoint: []
    command: ["ollama", "serve"]
    profiles:
      - cpu

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - LOG_LEVEL=DEBUG
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    pull_policy: always

volumes:
  ollama_data:
  openwebui_data:
